### ISSUE TITLE
Add package related files

### ISSUE THREAD

**Issue by ramonsaraiva** [ramonsaraiva/pictory#3]
This still needs a few files to be uploaded to PyPI as a package:

- setup.py
- whatever is needed to use `pictory` as a command/executable

**Comment by brunabazaluk** [comment]
could it be written in bash?
or it must be python ?

**Comment by ramonsaraiva** [comment]
setup.py is a file that contains the meta data of the package, so it should be Python, yeah

**Comment by ramonsaraiva** [comment]
Added on https://github.com/ramonsaraiva/pictory/pull/4
